import sys
sys.stdout.reconfigure(encoding='utf-8')

bt = chr(96)  # backtick

# Build the file line by line to avoid f-string issues
lines = []
lines.append('/**')
lines.append(' * Hero.jsx - Hero principal con animaciones avanzadas')
lines.append(' */')
lines.append('')
lines.append("import { Link } from 'react-router-dom';")
lines.append("import { motion } from 'framer-motion';")
lines.append("import { useEffect, useState } from 'react';")
lines.append('')
lines.append('const containerVariants = {')
lines.append('  hidden: {},')
lines.append('  visible: {')
lines.append("    transition: { staggerChildren: 0.08, delayChildren: 0.2 },")
lines.append('  },')
lines.append('};')
lines.append('')
lines.append('const wordVariants = {')
lines.append("  hidden: { opacity: 0, y: 40, filter: 'blur(10px)' },")
lines.append('  visible: {')
lines.append('    opacity: 1,')
lines.append('    y: 0,')
lines.append("    filter: 'blur(0px)',")
lines.append('    transition: { duration: 0.6, ease: [0.25, 0.46, 0.45, 0.94] },')
lines.append('  },')
lines.append('};')
lines.append('')
lines.append('const fadeUp = {')
lines.append('  hidden: { opacity: 0, y: 30 },')
lines.append('  visible: { opacity: 1, y: 0, transition: { duration: 0.6, delay: 0.6 } },')
lines.append('};')
lines.append('')
lines.append('export default function Hero() {')
lines.append('  const [mousePos, setMousePos] = useState({ x: 0, y: 0 });')
lines.append('')
lines.append('  useEffect(() => {')
lines.append("    const handleMouseMove = (e) => {")
lines.append("      const rect = document.getElementById('hero-media')?.getBoundingClientRect();")
lines.append("      if (!rect) return;")
lines.append("      const x = ((e.clientX - rect.left) / rect.width - 0.5) * 12;")
lines.append("      const y = ((e.clientY - rect.top) / rect.height - 0.5) * -12;")
lines.append("      setMousePos({ x, y });")
lines.append("    };")
lines.append("    window.addEventListener('mousemove', handleMouseMove);")
lines.append("    return () => window.removeEventListener('mousemove', handleMouseMove);")
lines.append("  }, []);")
lines.append('')
lines.append("  const titleWords = ['Perfumes', 'que', 'enamoran'];")
lines.append('')
lines.append('  return (')
lines.append('    <section className="hero" role="banner">')
lines.append('      <div className="hero-particles" aria-hidden="true">')
lines.append('        {[...Array(6)].map((_, i) => (')
lines.append('          <div')
lines.append('            key={i}')
lines.append('            className="hero-particle"')
lines.append('            style={{')
lines.append(f'              left: {bt}' + '' + f'{bt},')
lines.append(f'              top: {bt}' + '' + f'{bt},')
lines.append(f'              width: {bt}' + '' + f'{bt}px,')
lines.append(f'              height: {bt}' + '' + f'{bt}px,')
lines.append(f'              animationDelay: {bt}' + '' + f'{bt}s,')
lines.append(f'              animationDuration: {bt}' + '' + f'{bt}s,')
lines.append('            }}')
lines.append('          />')
lines.append('        ))}')
lines.append('      </div>')
lines.append('')
lines.append('      <div className="container hero-inner">')
lines.append('        <motion.div')
lines.append('          className="hero-copy"')
lines.append('          variants={containerVariants}')
lines.append('          initial="hidden"')
lines.append('          animate="visible"')
lines.append('        >')
lines.append('          <motion.div className="hero-badge" variants={fadeUp}>')
lines.append('            <span className="hero-badge-dot" />')
lines.append('            Nuevas fragancias 2025')
lines.append('          </motion.div>')
lines.append('')
lines.append('          <motion.h1 variants={containerVariants}>')
lines.append('            {titleWords.map((word, i) => (')
lines.append('              <motion.span')
lines.append('                key={i}')
lines.append('                variants={wordVariants}')
lines.append("                style={{ display: 'inline-block', marginRight: '0.35em' }}")
lines.append('              >')
lines.append('                {i === 2 ? <span className="hero-highlight">{word}</span> : word}')
lines.append('              </motion.span>')
lines.append('            ))}')
lines.append('          </motion.h1>')
lines.append('')
lines.append('          <motion.p variants={fadeUp}>')
lines.append('            Fragancias originales Lattafa, Armaf y m&aacute;s, con env&iacute;o r&aacute;pido y asesor&iacute;a personal por WhatsApp.')
lines.append('          </motion.p>')
lines.append('')
lines.append('          <motion.div className="hero-cta" variants={fadeUp}>')
lines.append('            <Link to="/tienda" className="btn btn-primary btn-hero">')
lines.append('              Explorar tienda')
lines.append('            </Link>')
lines.append('            <Link to="/nosotros" className="btn btn-outline btn-hero">')
lines.append('              Con&oacute;cenos')
lines.append('            </Link>')
lines.append('          </motion.div>')
lines.append('')
lines.append('          <motion.div className="hero-social" variants={fadeUp}>')
lines.append('            <div className="hero-avatars">')
lines.append("              <div className=\"hero-avatar\" style={{backgroundImage: 'url(https://i.pravatar.cc/32?img=1)'}} />")
lines.append("              <div className=\"hero-avatar\" style={{backgroundImage: 'url(https://i.pravatar.cc/32?img=5)'}} />")
lines.append("              <div className=\"hero-avatar\" style={{backgroundImage: 'url(https://i.pravatar.cc/32?img=8)'}} />")
lines.append("              <div className=\"hero-avatar\" style={{backgroundImage: 'url(https://i.pravatar.cc/32?img=11)'}} />")
lines.append('              <div className="hero-avatar hero-avatar--more">+</div>')
lines.append('            </div>')
lines.append('            <div className="hero-stars">')
lines.append('              <span className="hero-stars-icons">★★★★★</span>')
lines.append('              <span className="hero-stars-text">4.8/5 &middot; 200+ rese&ntilde;as</span>')
lines.append('            </div>')
lines.append('          </motion.div>')
lines.append('        </motion.div>')
lines.append('')
lines.append('        <div className="hero-media" id="hero-media" role="img" aria-label="Colecci&oacute;n de perfumes originales tng_shops">')
lines.append('          <div className="hero-rings" aria-hidden="true">')
lines.append('            <div className="hero-ring" />')
lines.append('            <div className="hero-ring hero-ring--slow" />')
lines.append('            <div className="hero-ring hero-ring--slowest" />')
lines.append('          </div>')
lines.append('')
lines.append('          <div className="hero-glow" aria-hidden="true" />')
lines.append('          <div className="hero-glow hero-glow--alt" aria-hidden="true" />')
lines.append('')
lines.append('          <motion.div')
lines.append('            className="hero-image-wrapper"')
lines.append('            animate={{')
lines.append('              rotateX: mousePos.y,')
lines.append('              rotateY: mousePos.x,')
lines.append('            }}')
lines.append('            transition={{ type: "spring", stiffness: 50, damping: 20 }}')
lines.append('          >')
lines.append('            <div className="hero-image-glass" />')
lines.append('            <img')
lines.append('              src="/images/bannerTng_shops.png"')
lines.append('              alt="Colecci&oacute;n de perfumes originales tng_shops"')
lines.append('              className="banner-img"')
lines.append('            />')
lines.append('          </motion.div>')
lines.append('        </div>')
lines.append('      </div>')
lines.append('')
lines.append('      <motion.div')
lines.append('        className="scroll-indicator"')
lines.append('        initial={{ opacity: 0 }}')
lines.append('        animate={{ opacity: 1 }}')
lines.append('        transition={{ delay: 1.5 }}')
lines.append('        aria-hidden="true"')
lines.append('      >')
lines.append('        <span className="scroll-text">Scroll</span>')
lines.append('        <div className="scroll-line">')
lines.append('          <motion.div')
lines.append('            className="scroll-dot"')
lines.append('            animate={{ y: [0, 16, 0] }}')
lines.append("            transition={{ duration: 1.8, repeat: Infinity, ease: 'easeInOut' }}")
lines.append('          />')
lines.append('        </div>')
lines.append('      </motion.div>')
lines.append('    </section>')
lines.append('  );')
lines.append('}')
lines.append('')

with open(r'D:\TNGSHOPS\PaginaWeb\src\components\Hero.jsx', 'w', encoding='utf-8') as f:
    f.write('\n'.join(lines))

print('Hero.jsx written successfully with', len(lines), 'lines')